
/*
 * conf_the_artist_front.h
 *
 * Created: 4/6/2017 8:21:02 PM
 *  Author: credtiger96@gmail.com 
 
 */ 
#define CONF_ARTIST_BAUDRATE	9600 

#define		CONF_ARTIST_CENTER_ULTRASONIC_ECHO_PIN		PIN_PA13
#define		CONF_ARTIST_LEFT_ULTRASONIC_ECHO_PIN		PIN_PA23
#define		CONF_ARTIST_RIGHT_ULTRASONIC_ECHO_PIN		PIN_PA28
#define		CONF_ARTIST_ULTRASONIC_TRIGGER_PIN			PIN_PA15

#define		CONF_ARTIST_ULTRASONIC_FILTERVAL			0.6
#define		CONF_ARTIST_ULTRASONIC_THRESHOLD			4.0



#define		MAX_FRAME_SIZE								30
#define		MAX_ACK_SIZE								5
#define		ARTIST_FRONT_ADDR							0x0B
#define		ARTIST_GROUND_ADDR							0x0A
#define		ARTIST_CHANNEL								0x0E
