
/*
 * conf_the_artisth.S
 *
 * Created: 4/5/2017 2:38:51 PM
 *  Author: credt
 */ 

 #define CONF_ARTIST_BAUDRATE  9600 

#define CONF_ARTIST_MOTOR_1_PWM_PIN				PIN_PA18F_TCC0_WO2
#define CONF_ARTIST_MOTOR_2_PWM_PIN				PIN_PA19F_TCC0_WO3 
#define CONF_ARTIST_MOTOR_1_PWM_MUX				MUX_PA18F_TCC0_WO2
#define CONF_ARTIST_MOTOR_2_PWM_MUX				MUX_PA19F_TCC0_WO3
#define CONF_ARTIST_MOTOR_1_PWM_OUTPUT			2
#define CONF_ARTIST_MOTOR_2_PWM_OUTPUT			3
#define CONF_ARTIST_MOTOR_1_PWM_CHANNEL			2
#define CONF_ARTIST_MOTOR_2_PWM_CHANNEL			3

#define CONF_ARTIST_MOTOR_PWM_STOP				0x0000
#define CONF_ARTIST_MOTOR_PWM_FORWORD			0x2FFF
#define CONF_ARTIST_MOTOR_PWM_BACKWORD			0x0FFF				